[2023-04-05T16:34:06.750+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_dag_with_python_operator_v01.greet scheduled__2022-02-28T00:00:00+00:00 [queued]>
[2023-04-05T16:34:06.772+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_dag_with_python_operator_v01.greet scheduled__2022-02-28T00:00:00+00:00 [queued]>
[2023-04-05T16:34:06.772+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-05T16:34:06.772+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 6
[2023-04-05T16:34:06.772+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-05T16:34:06.826+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): greet> on 2022-02-28 00:00:00+00:00
[2023-04-05T16:34:06.832+0000] {standard_task_runner.py:55} INFO - Started process 633 to run task
[2023-04-05T16:34:06.838+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'create_dag_with_python_operator_v01', 'greet', 'scheduled__2022-02-28T00:00:00+00:00', '--job-id', '2348', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmpc5hw20ug']
[2023-04-05T16:34:06.840+0000] {standard_task_runner.py:83} INFO - Job 2348: Subtask greet
[2023-04-05T16:34:06.930+0000] {task_command.py:389} INFO - Running <TaskInstance: create_dag_with_python_operator_v01.greet scheduled__2022-02-28T00:00:00+00:00 [running]> on host 5c67bb0a0ff3
[2023-04-05T16:34:07.086+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=dejan
AIRFLOW_CTX_DAG_ID=create_dag_with_python_operator_v01
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2022-02-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-28T00:00:00+00:00
[2023-04-05T16:34:07.087+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: greet() missing 2 required positional arguments: 'name' and 'age'
[2023-04-05T16:34:07.104+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=create_dag_with_python_operator_v01, task_id=greet, execution_date=20220228T000000, start_date=20230405T163406, end_date=20230405T163407
[2023-04-05T16:34:07.122+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2348 for task greet (greet() missing 2 required positional arguments: 'name' and 'age'; 633)
[2023-04-05T16:34:07.137+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-05T16:34:07.198+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
