[2023-04-05T16:34:05.132+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_dag_with_python_operator_v01.greet scheduled__2022-02-21T00:00:00+00:00 [queued]>
[2023-04-05T16:34:05.155+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_dag_with_python_operator_v01.greet scheduled__2022-02-21T00:00:00+00:00 [queued]>
[2023-04-05T16:34:05.155+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-05T16:34:05.156+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 6
[2023-04-05T16:34:05.156+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-05T16:34:05.185+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): greet> on 2022-02-21 00:00:00+00:00
[2023-04-05T16:34:05.191+0000] {standard_task_runner.py:55} INFO - Started process 619 to run task
[2023-04-05T16:34:05.203+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'create_dag_with_python_operator_v01', 'greet', 'scheduled__2022-02-21T00:00:00+00:00', '--job-id', '2341', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmp4wcmzeiq']
[2023-04-05T16:34:05.205+0000] {standard_task_runner.py:83} INFO - Job 2341: Subtask greet
[2023-04-05T16:34:05.312+0000] {task_command.py:389} INFO - Running <TaskInstance: create_dag_with_python_operator_v01.greet scheduled__2022-02-21T00:00:00+00:00 [running]> on host 5c67bb0a0ff3
[2023-04-05T16:34:05.468+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=dejan
AIRFLOW_CTX_DAG_ID=create_dag_with_python_operator_v01
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2022-02-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-21T00:00:00+00:00
[2023-04-05T16:34:05.468+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: greet() missing 2 required positional arguments: 'name' and 'age'
[2023-04-05T16:34:05.480+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=create_dag_with_python_operator_v01, task_id=greet, execution_date=20220221T000000, start_date=20230405T163405, end_date=20230405T163405
[2023-04-05T16:34:05.503+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2341 for task greet (greet() missing 2 required positional arguments: 'name' and 'age'; 619)
[2023-04-05T16:34:05.521+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-05T16:34:05.553+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
