[2023-04-06T13:32:05.655+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_dag_with_python_operator_v06.get_name scheduled__2022-05-26T00:00:00+00:00 [queued]>
[2023-04-06T13:32:05.694+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_dag_with_python_operator_v06.get_name scheduled__2022-05-26T00:00:00+00:00 [queued]>
[2023-04-06T13:32:05.694+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-06T13:32:05.694+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 6
[2023-04-06T13:32:05.698+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-06T13:32:05.826+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): get_name> on 2022-05-26 00:00:00+00:00
[2023-04-06T13:32:05.846+0000] {standard_task_runner.py:55} INFO - Started process 4681 to run task
[2023-04-06T13:32:05.876+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'create_dag_with_python_operator_v06', 'get_name', 'scheduled__2022-05-26T00:00:00+00:00', '--job-id', '4641', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmpzivuh0rz']
[2023-04-06T13:32:05.883+0000] {standard_task_runner.py:83} INFO - Job 4641: Subtask get_name
[2023-04-06T13:32:06.171+0000] {task_command.py:389} INFO - Running <TaskInstance: create_dag_with_python_operator_v06.get_name scheduled__2022-05-26T00:00:00+00:00 [running]> on host 971eab773426
[2023-04-06T13:32:06.508+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=dejan
AIRFLOW_CTX_DAG_ID=create_dag_with_python_operator_v06
AIRFLOW_CTX_TASK_ID=get_name
AIRFLOW_CTX_EXECUTION_DATE=2022-05-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-26T00:00:00+00:00
[2023-04-06T13:32:06.554+0000] {local_task_job.py:113} ERROR - Received SIGTERM. Terminating subprocesses
[2023-04-06T13:32:06.557+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 4681. PIDs of all processes in the group: [4681]
[2023-04-06T13:32:06.557+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 4681
[2023-04-06T13:32:06.565+0000] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-04-06T13:32:06.626+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 19, in get_name
    ti.xcom_push(key = 'first_name', value='Dejan')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2305, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 209, in set
    dag_run_id = session.query(DagRun.id).filter_by(dag_id=dag_id, run_id=run_id).scalar()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2893, in scalar
    ret = self.one()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2870, in one
    return self._iter().one()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2919, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 335, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1944, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2128, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.7/encodings/utf_8.py", line 15, in decode
    def decode(input, errors='strict'):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1490, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-04-06T13:32:06.665+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=create_dag_with_python_operator_v06, task_id=get_name, execution_date=20220526T000000, start_date=20230406T133205, end_date=20230406T133206
[2023-04-06T13:32:06.737+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4641 for task get_name (Task received SIGTERM signal; 4681)
[2023-04-06T13:32:06.752+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=4681, status='terminated', exitcode=1, started='13:32:05') (4681) terminated with exit code 1
[2023-04-06T13:32:06.753+0000] {local_task_job.py:212} INFO - Task exited with return code 143
[2023-04-06T13:32:06.862+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
