[2023-04-10T15:30:45.886+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgress_hooks_v01.postgres_to_s3 manual__2023-04-10T15:30:44.804350+00:00 [queued]>
[2023-04-10T15:30:45.897+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgress_hooks_v01.postgres_to_s3 manual__2023-04-10T15:30:44.804350+00:00 [queued]>
[2023-04-10T15:30:45.897+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-10T15:30:45.897+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 6
[2023-04-10T15:30:45.898+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-10T15:30:45.921+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2023-04-10 15:30:44.804350+00:00
[2023-04-10T15:30:45.925+0000] {standard_task_runner.py:55} INFO - Started process 1350 to run task
[2023-04-10T15:30:45.927+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgress_hooks_v01', 'postgres_to_s3', 'manual__2023-04-10T15:30:44.804350+00:00', '--job-id', '7066', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgress_hooks.py', '--cfg-path', '/tmp/tmp6qy6tzv_']
[2023-04-10T15:30:45.928+0000] {standard_task_runner.py:83} INFO - Job 7066: Subtask postgres_to_s3
[2023-04-10T15:30:45.987+0000] {task_command.py:389} INFO - Running <TaskInstance: dag_with_postgress_hooks_v01.postgres_to_s3 manual__2023-04-10T15:30:44.804350+00:00 [running]> on host d034b084d02f
[2023-04-10T15:30:46.082+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=dejan
AIRFLOW_CTX_DAG_ID=dag_with_postgress_hooks_v01
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-04-10T15:30:44.804350+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-10T15:30:44.804350+00:00
[2023-04-10T15:30:46.099+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgress_hooks.py", line 19, in postgres_to_s3
    conn = hook.get_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 117, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2023-04-10T15:30:46.104+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgress_hooks_v01, task_id=postgres_to_s3, execution_date=20230410T153044, start_date=20230410T153045, end_date=20230410T153046
[2023-04-10T15:30:46.117+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 7066 for task postgres_to_s3 (The conn_id `postgres_default` isn't defined; 1350)
[2023-04-10T15:30:46.144+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-10T15:30:46.167+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
