[2023-04-06T13:15:43.362+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_dag_with_python_operator_v05.greet scheduled__2021-10-15T00:00:00+00:00 [queued]>
[2023-04-06T13:15:43.379+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_dag_with_python_operator_v05.greet scheduled__2021-10-15T00:00:00+00:00 [queued]>
[2023-04-06T13:15:43.380+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-06T13:15:43.380+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 6
[2023-04-06T13:15:43.380+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-06T13:15:43.453+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): greet> on 2021-10-15 00:00:00+00:00
[2023-04-06T13:15:43.492+0000] {standard_task_runner.py:55} INFO - Started process 1366 to run task
[2023-04-06T13:15:43.514+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'create_dag_with_python_operator_v05', 'greet', 'scheduled__2021-10-15T00:00:00+00:00', '--job-id', '3240', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmpn800g7lq']
[2023-04-06T13:15:43.528+0000] {standard_task_runner.py:83} INFO - Job 3240: Subtask greet
[2023-04-06T13:15:43.726+0000] {task_command.py:389} INFO - Running <TaskInstance: create_dag_with_python_operator_v05.greet scheduled__2021-10-15T00:00:00+00:00 [running]> on host 971eab773426
[2023-04-06T13:15:43.956+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=dejan
AIRFLOW_CTX_DAG_ID=create_dag_with_python_operator_v05
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2021-10-15T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-15T00:00:00+00:00
[2023-04-06T13:15:43.960+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 13, in greet
    first_name = ti.xcom_pull(task_ids = 'get_name', key_ = 'first_name')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got an unexpected keyword argument 'key_'
[2023-04-06T13:15:43.976+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=create_dag_with_python_operator_v05, task_id=greet, execution_date=20211015T000000, start_date=20230406T131543, end_date=20230406T131543
[2023-04-06T13:15:44.001+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3240 for task greet (xcom_pull() got an unexpected keyword argument 'key_'; 1366)
[2023-04-06T13:15:44.042+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-06T13:15:44.150+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
