[2023-04-05T16:34:07.196+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_dag_with_python_operator_v01.greet scheduled__2022-03-02T00:00:00+00:00 [queued]>
[2023-04-05T16:34:07.208+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_dag_with_python_operator_v01.greet scheduled__2022-03-02T00:00:00+00:00 [queued]>
[2023-04-05T16:34:07.209+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-05T16:34:07.210+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 6
[2023-04-05T16:34:07.210+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-05T16:34:07.243+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): greet> on 2022-03-02 00:00:00+00:00
[2023-04-05T16:34:07.250+0000] {standard_task_runner.py:55} INFO - Started process 637 to run task
[2023-04-05T16:34:07.261+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'create_dag_with_python_operator_v01', 'greet', 'scheduled__2022-03-02T00:00:00+00:00', '--job-id', '2350', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmp1gdmdosg']
[2023-04-05T16:34:07.263+0000] {standard_task_runner.py:83} INFO - Job 2350: Subtask greet
[2023-04-05T16:34:07.373+0000] {task_command.py:389} INFO - Running <TaskInstance: create_dag_with_python_operator_v01.greet scheduled__2022-03-02T00:00:00+00:00 [running]> on host 5c67bb0a0ff3
[2023-04-05T16:34:07.506+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=dejan
AIRFLOW_CTX_DAG_ID=create_dag_with_python_operator_v01
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2022-03-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-02T00:00:00+00:00
[2023-04-05T16:34:07.506+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: greet() missing 2 required positional arguments: 'name' and 'age'
[2023-04-05T16:34:07.523+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=create_dag_with_python_operator_v01, task_id=greet, execution_date=20220302T000000, start_date=20230405T163407, end_date=20230405T163407
[2023-04-05T16:34:07.558+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2350 for task greet (greet() missing 2 required positional arguments: 'name' and 'age'; 637)
[2023-04-05T16:34:07.603+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-05T16:34:07.787+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
