[2023-04-06T13:05:03.408+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_dag_with_python_operator_v04.greet scheduled__2021-10-09T00:00:00+00:00 [queued]>
[2023-04-06T13:05:03.441+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_dag_with_python_operator_v04.greet scheduled__2021-10-09T00:00:00+00:00 [queued]>
[2023-04-06T13:05:03.441+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-06T13:05:03.441+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 6
[2023-04-06T13:05:03.442+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-06T13:05:03.670+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): greet> on 2021-10-09 00:00:00+00:00
[2023-04-06T13:05:03.686+0000] {standard_task_runner.py:55} INFO - Started process 561 to run task
[2023-04-06T13:05:03.692+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'create_dag_with_python_operator_v04', 'greet', 'scheduled__2021-10-09T00:00:00+00:00', '--job-id', '3007', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmpc6fila9s']
[2023-04-06T13:05:03.694+0000] {standard_task_runner.py:83} INFO - Job 3007: Subtask greet
[2023-04-06T13:05:03.931+0000] {task_command.py:389} INFO - Running <TaskInstance: create_dag_with_python_operator_v04.greet scheduled__2021-10-09T00:00:00+00:00 [running]> on host 971eab773426
[2023-04-06T13:05:04.192+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=dejan
AIRFLOW_CTX_DAG_ID=create_dag_with_python_operator_v04
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2021-10-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-09T00:00:00+00:00
[2023-04-06T13:05:04.193+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 13, in greet
    name = ti.xcoms_pull(task_ids = 'get_name')
AttributeError: 'TaskInstance' object has no attribute 'xcoms_pull'
[2023-04-06T13:05:04.234+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=create_dag_with_python_operator_v04, task_id=greet, execution_date=20211009T000000, start_date=20230406T130503, end_date=20230406T130504
[2023-04-06T13:05:04.481+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3007 for task greet ('TaskInstance' object has no attribute 'xcoms_pull'; 561)
[2023-04-06T13:05:04.527+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-06T13:05:04.588+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
