[2023-04-05T16:34:04.536+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_dag_with_python_operator_v01.greet scheduled__2022-02-19T00:00:00+00:00 [queued]>
[2023-04-05T16:34:04.549+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_dag_with_python_operator_v01.greet scheduled__2022-02-19T00:00:00+00:00 [queued]>
[2023-04-05T16:34:04.549+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-05T16:34:04.549+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 6
[2023-04-05T16:34:04.549+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-05T16:34:04.570+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): greet> on 2022-02-19 00:00:00+00:00
[2023-04-05T16:34:04.574+0000] {standard_task_runner.py:55} INFO - Started process 614 to run task
[2023-04-05T16:34:04.576+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'create_dag_with_python_operator_v01', 'greet', 'scheduled__2022-02-19T00:00:00+00:00', '--job-id', '2339', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmplj064rw9']
[2023-04-05T16:34:04.578+0000] {standard_task_runner.py:83} INFO - Job 2339: Subtask greet
[2023-04-05T16:34:04.650+0000] {task_command.py:389} INFO - Running <TaskInstance: create_dag_with_python_operator_v01.greet scheduled__2022-02-19T00:00:00+00:00 [running]> on host 5c67bb0a0ff3
[2023-04-05T16:34:04.786+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=dejan
AIRFLOW_CTX_DAG_ID=create_dag_with_python_operator_v01
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2022-02-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-19T00:00:00+00:00
[2023-04-05T16:34:04.787+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: greet() missing 2 required positional arguments: 'name' and 'age'
[2023-04-05T16:34:04.800+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=create_dag_with_python_operator_v01, task_id=greet, execution_date=20220219T000000, start_date=20230405T163404, end_date=20230405T163404
[2023-04-05T16:34:04.818+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2339 for task greet (greet() missing 2 required positional arguments: 'name' and 'age'; 614)
[2023-04-05T16:34:04.833+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-05T16:34:04.880+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
